name: kessel
types:
    lock:
        visibility: internal
        relations:
            version:
                visibility: public
                body:
                    kind: assignable
                    types:
                        - name: lockversion
                    cardinality: ExactlyOne
    lockversion:
        visibility: internal
        relations: {}
