on:
  pull_request:
    branches:
      - master
    paths:
      - configs/stage/schemas/src/**
      - configs/stage/permissions/**
      - configs/prod/schemas/src/**
      - configs/prod/permissions/**
      - configs/stage/schemas/schema.zed
      - configs/prod/schemas/schema.zed
permissions:
  contents: write
name: Schema generation & validation
jobs:
  generate_schema:
    name: Generate & Validate Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      # generate ksil json file
      - name: Run Generate V1-Only Permissions Data for stage
        uses: wscalf/rbac-config-actions/generate-v1-only-permissions@add-generate-v1-only-permissions-action
        with:
          ksl: configs/stage/schemas
          rbac_permissions: configs/stage/permissions

      - name: Run Generate V1-Only Permissions Data for prod
        uses: wscalf/rbac-config-actions/generate-v1-only-permissions@add-generate-v1-only-permissions-action
        with:
          ksl: configs/prod/schemas
          rbac_permissions: configs/prod/permissions

      # generate schemas
      - name: Clone ksl-schema-language repo
        run: git clone --depth=1 https://github.com/project-kessel/ksl-schema-language.git

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
      
      - name: Build KSL compiler binary
        run: |
          cd ksl-schema-language
          mkdir -p bin/
          go build -gcflags "all=-N -l" -o ./bin/ ./...
          cd ..

      - name: Run KSL compiler
        run: |
          ./ksl-schema-language/bin/ksl -o configs/stage/schemas/schema.zed configs/stage/schemas/src/*.ksl configs/stage/schemas/src/*.json
          ./ksl-schema-language/bin/ksl -o configs/prod/schemas/schema.zed configs/prod/schemas/src/*.ksl configs/prod/schemas/src/*.json

      - name: Remove KSL repo & ksil files
        run: |
          rm -rf ksl-schema-language/
          rm configs/stage/schemas/src/rbac_v1_permissions.json
          rm configs/prod/schemas/src/rbac_v1_permissions.json

      # validate generated schemas
      - name: Validate Stage Schema
        uses: "authzed/action-spicedb-validate@v1"
        with:
          validationfile: "configs/stage/schemas/schema.zed"
      - name: Validate Prod Schema
        uses: "authzed/action-spicedb-validate@v1"
        with:
          validationfile: "configs/prod/schemas/schema.zed"

      # commit changed schema back to PR.
      - uses: stefanzweifel/git-auto-commit-action@v5
